### ISSUE TITLE
use YAML for config input file

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#1]
The ini format used for cfg files is limiting. Switch to yaml.

* [x] implement yaml parsing
* [x] provide translator script to rewrite old cfg files as yml

**Comment by ianmkenney** [comment]
I am looking into ways to get yaml parsing. Do we want to write our own or use something like pyyaml.org?

**Comment by orbeckst** [comment]
Never roll your own if you can use a tested library!

It needs to be something that can be installed via pip.

Maybe @dotsdl has any suggestions.

On 11 Dec, 2015, at 21:47, Ian Kenney wrote:

> I am looking into ways to get yaml parsing. Do we want to write our own or use something like pyyaml.org?
> 
> �
> Reply to this email directly or view it on GitHub.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by dotsdl** [comment]
Just use [PyYAML](https://pypi.python.org/pypi/PyYAML).

**Comment by ianmkenney** [comment]
Closing.

**Comment by orbeckst** [comment]
Is this fixed in a commit? If so, add to the commit comment `closes #1` and it will be automatically referenced here. Otherwise, give the SHA1 of the commit in your manual closing message.

**Comment by ianmkenney** [comment]
closed with 13110a5f43fd21f35db10c5a736e99e385d3de67

**Comment by ianmkenney** [comment]
Closing the reopened issue... sha1: 13110a5f43fd21f35db10c5a736e99e385d3de67
