### ISSUE TITLE
scripts for analyzing cyclohexane simulations

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#11]
The current develop branch does not install a script similar to `mdpow-ghyd` that computes the solvation energy in cyclohexane.

(There's also no such script of octanol so we really should have a general `mdpow-solvationenergy --solvent=<SOLVENT>` script.)

**Comment by ianmkenney** [comment]
syntax:
   mdpow-solvationenergy --solvent=<supported solvent> <directory (i.e. SAMPL_XXX)>

closed with sha1: 4db62b5998bf0b3dbc8451f098bc2f90f88e513c
