### ISSUE TITLE
mixed solvents are only support with Gromacs 2018 and higher versions

### ISSUE THREAD

**Issue by VOD555** [Becksteinlab/MDPOW#111]
Based on the tests on our local workstation, Gromacs with version 2018.6 _or higher_ support mixed molecule solvent. And the solvation process in MDPOW which modifies the topology file would make the `top` file mismatch the `gro` file generated after solvation.

Maybe we can use Gromacs preprocessor directives in the file and define a variable `MDPOWPREGMX2019` (As discussed in PR #103 )

```
DRUG               1
#ifdef MDPOWPREGMX2019
OcOH               1
#endif
```

And then add to to the MDP file:
```
define  = -DMDPOWPREGMX2019
```

**Comment by VOD555** [comment]
Current version supports GROMACS with version >2018, but doesn't support lower versions.

**Comment by orbeckst** [comment]
that's ok, we just have to document it and fail when we detect unsupported gmx

**Comment by orbeckst** [comment]
Is this why our Gromacs 4.6.5 tests fail?

**Comment by orbeckst** [comment]
yes

**Comment by orbeckst** [comment]
WIll mark the failing mixed solvent tests with XFAIL for 4.6.5

**Comment by orbeckst** [comment]
2018 also works, as see in the tests for #159

**Comment by orbeckst** [comment]
It's not worth our time to make this work for 4.6.5 (and 5?) — I am closing with a won't fix. The XFAIL test references this issue.
