### ISSUE TITLE
MDPOW does not use TIP3P for CHARMM and AMBER for hydration free energy calculation by default

### ISSUE THREAD

**Issue by VOD555** [Becksteinlab/MDPOW#112]
The way how mdpow selects water models is different from other solvents. Current mdpow uses TIP4P for all force fields, but for CHARMM and AMBER  we should use TIP3P.

This is the problem with the `get_solvent_model` function in `forcefields.py`.

**Comment by orbeckst** [comment]
@VOD555 but for SAMPL6 we ran our CHARMM simulations with TIP3P, at least that's what we wrote (and clarified) in the README for https://github.com/Becksteinlab/SAMPL6_logP_data . How did we do this then?

**Comment by VOD555** [comment]
@orbeckst This happens when you set the solvent = water without specific water model. One can choose tip3p using the option watermodel, but the default watermodel for all forcefield is tip4p. 
See line 124 in `forcefield.py`

**Comment by orbeckst** [comment]
Thanks for clarifying.

It would be good to have a way to change FF #123 and then, based on that setting, choose the defaults.

**Comment by orbeckst** [comment]
Is this related to #140 ?

cc @iorga

**Comment by iorga** [comment]
@orbeckst No, not directly related to #140. The idea is to choose automatically, in the absence of the solventmodel/watermodel option, the right water model, which is tip3p for AMBER and CHARMM (similarly with OPLS-AA which choses tip4p).

**Comment by orbeckst** [comment]
This is a "nice to have" – it's not required for 0.7.0.

**Comment by orbeckst** [comment]
@VOD555 do we want this fixed for 0.8.0 ?

**Comment by EliasCoba** [comment]
Hello, i'm a new user of MDPow, also new in GitHub. I'm using the mdpow scripts in YAML format and the OPLS ff, I would like to use SPC/E as water model with OPLS calculation, but when I use the keyword as: **_watermodel: "spce"_**, in the simulations, topology is always based in tip4p, there is something that i'm doing incorrect?

**Comment by iorga** [comment]
Hello @EliasCoba, 

Thank you for using MDPOW. As shown in the template `runinput.yml` file (https://github.com/Becksteinlab/MDPOW/blob/develop/mdpow/templates/runinput.yml), you should use "solventmodel: spce". "watermodel" is the old syntax, which is now deprecated, and probably is not functional anymore.

Please also tell us where did you find this syntax in the documentation, so we can correct it.

Best regards,
Bogdan

**Comment by EliasCoba** [comment]
Thank you for your advice @iorga, 

I employed the template runinput.yml and it works perfect. The first yml file, I got it from https://mdpow.readthedocs.io/en/latest/init.html, in the section "[2.3. Tutorial: Using the mdpow scripts to compute log POW of benzene](https://mdpow.readthedocs.io/en/latest/init.html#tutorial-using-the-mdpow-scripts-to-compute-logpow-of-benzene)", there is an hyperlink to a `benzene.yml` file using watermodel keyword.

One last question, maybe this is out of topic. I would like to use GROMOS54A7 ff with MDPow, I have read that it is not hard to do but requires tedious changes to a few paths in template scripts, what is important to take in account? which scripts are critical? and what happen if I just change the files of a topology already included, for example of OPLS and put the GROMOS54A7 files.

**Comment by orbeckst** [comment]
@EliasCoba could you please use https://github.com/Becksteinlab/MDPOW/discussions for general questions that are not specific to an existing issue? (I'm sorry, we haven't made this clear anywhere yet.)

**Comment by orbeckst** [comment]
> I employed the template runinput.yml and it works perfect. The first yml file, I got it from https://mdpow.readthedocs.io/en/latest/init.html, in the section "[2.3. Tutorial: Using the mdpow scripts to compute log POW of benzene](https://mdpow.readthedocs.io/en/latest/init.html#tutorial-using-the-mdpow-scripts-to-compute-logpow-of-benzene)", there is an hyperlink to a benzene.yml file using watermodel keyword.

Thank you for pointing out the outdated example file!!

**Comment by EliasCoba** [comment]
Thanks for the clarification @orbeckst, I will create a new discussion in that section.

**Comment by iorga** [comment]
> One last question, maybe this is out of topic. I would like to use GROMOS54A7 ff with MDPow, I have read that it is not hard to do but requires tedious changes to a few paths in template scripts, what is important to take in account? which scripts are critical? and what happen if I just change the files of a topology already included, for example of OPLS and put the GROMOS54A7 files.

@EliasCoba This might be possible, but it requires some work. The force field parameters from the GROMACS xxxx.ff folders are important, and should be imported in MDPOW, and also the water models. Then the specific options for Gromos should be added to different scripts, choice of the right water model by default, etc. Please open a discussion for this topic in the discussions forum if you want to go further.
