### ISSUE TITLE
Update OPLS-AA octanol parameters

### ISSUE THREAD

**Issue by VOD555** [Becksteinlab/MDPOW#120]
As discussed in the paper, the octanol model used in MDPOW underwent a phase transition to a dense solid phase during the simulation at 273 K.
We should update with the parameters from Zangi R (2018) Refinement of the OPLSAA force-field for liquid alcohols. ACS Omega 3(12):18089–18099. https://doi-org.ezproxy1.lib.asu.edu/10.1021/acsomega.8b03132 .

**Comment by iorga** [comment]
I have generated the `1octnew.itp` file with the parameters from the paper (also added a new atom-type in the `ffnonbonded.itp` file), see the pull request #121. 

@VOD555 , can you please implement it in MDPOW as an alternative to `1oct.itp` or `1octwet.itp` ? Thanks. I will run simulations with both `1oct.itp` and `1octnew.itp`, so we can compare the results.

**Comment by iorga** [comment]
@VOD555 please don't forget to update also the script `mdpow-get-runinput` which generates the reference `runinput.yml` file. In the absence of updated documentation, this is the only resource for the user to see the available options and the syntax. Thanks.
