### ISSUE TITLE
allow mdpow analysis scripts to select alchemlyb estimators

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#133]
When PR #132 is merged, we can use alchemlyb (including MBAR #26 ) estimators instead of MDPOW TI from the python API. This should also be available from the commandline tools, especially `mdpow-fep`
- [x] commandline options
- [ ] cfg file options

(Decide if one or both.)

**Comment by orbeckst** [comment]
cc @iorga – please check here for progress

**Comment by VOD555** [comment]
Just found `mdpow-fep` only runs the simulations, the analyze scripts are `mdpow-pow`, `mdpow-ghyd` or `mdpow-solvationenergy`.

**Comment by VOD555** [comment]
Current `method` is a keyword for `mdpow-fep` in cfg file, but it only works when people use the analysis scripts. I prefer using commandline options for this version and have a new procedure `analysis` in cfg file in a future version.

**Comment by orbeckst** [comment]
I am fine with command line only for right now. But it should work with the files that we produced from SAMPL7.
