### ISSUE TITLE
allow mdpow other analysis scripts to select alchemlyb estimators

### ISSUE THREAD

**Issue by VOD555** [Becksteinlab/MDPOW#135]
In #134 we add alchemlyb estimator options to `mdpow-pow`.
The same options need to be added to 

- [x] `mdpow-pow`
- [x] `mdpow-pcw`
- [x] `mdpow-ghyd` 
- [ ] `mdpow-solvationenergy`

**Comment by orbeckst** [comment]
@VOD555 can you please check off the scripts in the main issue above that already have the options added (eg as part of PR #142) so that we know what else would need to be done here? Thanks.

**Comment by VOD555** [comment]
ghyd and solvationenergy still need to be updated.

**Comment by orbeckst** [comment]
@VOD555 can you please make some time to finish this issue, we need the other scripts. Thanks.

**Comment by orbeckst** [comment]
Note: all scripts should be consistent with each other and have the same interface.

**Comment by VOD555** [comment]
@orbeckst Just find in `ghyd` it says 
```
"The mdpow-ghyd script is DEPRECATED and will be removed in 0.7. "
"Use 'mdpow-solvationenergy --solvent=water' instead."
```

Do we need to modify the options for `ghyd` ?

**Comment by iorga** [comment]
@VOD555 No, `ghyd` should indeed be removed. We need to have `mdpow-solvationenergy` with the full functionality, which includes those of `ghyd`.
