### ISSUE TITLE
no backwards compatibility for the "watermodel" option of configuration file

### ISSUE THREAD

**Issue by iorga** [Becksteinlab/MDPOW#140]
The "watermodel" option of the configuration file that was present originally in MDPOW was replaced by the more general "solventmodel". Currently, when the "watermodel" option is present in the configuration file, MDPOW ignores it silently and uses the default water model, which is not the desired one.

The backwards compatibility should be ensured for this option.

**Comment by orbeckst** [comment]
How should this work? Should we just use *watermodel* as equivalent to *solventmodel*?

**Comment by orbeckst** [comment]
Or would it better to fail when *watermodel* is encountered?

**Comment by iorga** [comment]
Both options are fine for me. Probably use _watermodel_ as equivalent to _solventmodel_ is better, as in reality _solventmodel_ is a synonym of _watermodel_, but with broader applicability.

**Comment by orbeckst** [comment]
Given that we are still on 0.x and not API stable, I am going to close and we won't fix it.
