### ISSUE TITLE
options --SI and --no-SI in scripts should be mutually exclusive

### ISSUE THREAD

**Issue by iorga** [Becksteinlab/MDPOW#152]
- [ ] The `--SI` option activates the statistical inefficiency analysis and `--no-SI` disables it. The default value for `--SI` is `True` in the help message, which is correct, as this analysis is performed if no argument is provided. But in the same help message the default value for `--no-SI` is also `True`, which doesn't seem to be correct, as this analysis is not disabled in the absence of this argument. I suggest to change the default value for `--no-SI` in the help message to `False`.
- [ ] If both arguments `--SI` and `--no-SI` are provided simultaneously, no statistical inefficiency analysis is performed, so it seems that `--no-SI` prevails in these conditions. I consider that `--SI` and `--no-SI` are mutually exclusive and an error should be raised if they are used simultaneously.

**Comment by orbeckst** [comment]
Just fail if both are activated.

**Comment by VOD555** [comment]
`--SI` and `--no-SI` share the same variable `SI` which is the input for the solvation free energy calculation function. When using `--SI`, `SI` is set to be `True`, and when using `--no-SI`, `SI` is set to be `False`. I'll use another variable `noSI` for `--no-SI`.
These changes will be in #150

**Comment by orbeckst** [comment]
FIxed in PR #150
