### ISSUE TITLE
Adding Dihedral Analysis

### ISSUE THREAD

**Issue by ALescoulie** [Becksteinlab/MDPOW#190]
# MDPOW.analysis.dihedral

The dihedral analysis script will be build using `EnsembleAnalysis` to get the dihedrals for given atom groups. My plan is for it to take an `EnsembleAtomGroup` with four atoms selected from each system, then return the dihedrals in a DataFrame

- [x] Implement `DihdralAnalysis` class with EnsembleAnalysis 
- [x] Develop tests

**Comment by orbeckst** [comment]
@ALescoulie are you going to do the PR for changing Ensemble before pushing this one?

**Comment by ALescoulie** [comment]
Yeah, I'll get that one up soon

**Comment by ALescoulie** [comment]
@orbeckst the fix to `EnsembleAtomGroup.ensemble()` is up on PR #192, with that I'll be less concerned about passing a list of `EnsembleAtomGroups` into `DihedralAnalysis`. Do you want the analysis modules to be added via individual PRs.

**Comment by orbeckst** [comment]
Yes, make each analysis module a separate PR with a separate issue as this keeps discussion focused. It also helps if one thing turns out to be more complicated than others, then that won't hold up the others.
