### ISSUE TITLE
wrong MDP file for VDW FEP

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#20]
MDPOW currently creates **wrong mdp files for the VDW part of the FEP**: The FEP lines read

```
couple-lambda0 = vdw
couple-lambda1 = vdw-q
```

but this is **wrong** for the decoupling step where we switch off LJ.

Instead it **must** be

```
couple-lambda0 = vdw
couple-lambda1 = none
```

(as also indicated in the comments in the file itself!)

**Any simulations ran with this buggy version are WRONG.** I recommend deleting the whole FEP part and running anew (technically, the Coulomb part is correct but it can get messy figuring out what needs to be rerun so I advocated a clean slate).

**Comment by orbeckst** [comment]
@ianmkenney --- I am assigning this to you; please have a look asap. If I find the problem quickly I will notify you through the issue.

**Comment by ianmkenney** [comment]
on it

**Comment by orbeckst** [comment]
I think I introduced the bug when I "cleaned up" the parser...

**Comment by orbeckst** [comment]
I think I fixed it with PR #21. I am currently re-running methane. I will close the issue when the results are ok. I can already say, though, that the MDP file looks correct.

**Comment by orbeckst** [comment]
Comparison of the methane run to old runs gave the correct VDW contribution. Fixed!

**Comment by orbeckst** [comment]
Thanks to @iorga for comparison data.
