### ISSUE TITLE
DihedralAnalysis test_results_recursive2 fails most of the time

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#214]
The test for two dihedrals in DihedralAnalysis https://github.com/Becksteinlab/MDPOW/blob/2092cfd3f1cb006b38d01ec722dd2040f221a5c4/mdpow/tests/test_dihedral.py#L66-L83 started failing a few months ago with output like
```
 _____________________ TestDihedral.test_results_recursive2 _____________________

self = <mdpow.tests.test_dihedral.TestDihedral object at 0x7f0585e22070>

    def test_results_recursive2(self):
        dh1 = self.Ens.select_atoms('name C11 or name C10 or name C9 or name C4')
        dh2 = self.Ens.select_atoms('name C8 or name C4 or name C9 or name C10')
    
        dh_run = DihedralAnalysis([dh1, dh2]).run(start=0, stop=4, step=1)
    
        dh1_result = dh_run.results.loc[dh_run.results['selection'] == 'C4-C9-C10-C11']['dihedral']
        dh2_result = dh_run.results.loc[dh_run.results['selection'] == 'C4-C8-C9-C10']['dihedral']
    
        dh1_mean = circmean(dh1_result, high=180, low=-180)
        dh2_mean = circmean(dh2_result, high=180, low=-180)
        dh1_var = circvar(dh1_result, high=180, low=-180)
        dh2_var = circvar(dh2_result, high=180, low=-180)
    
        assert_almost_equal(self.DG48910_mean, dh1_mean, 6)
>       assert_almost_equal(self.DG48910_var, dh1_var, 6)
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E        ACTUAL: 1490.6576365537262
E        DESIRED: 0.20311120667628568
```
See, for instance, https://github.com/Becksteinlab/MDPOW/runs/7905279813?check_suite_focus=true#step:10:160 and https://github.com/Becksteinlab/MDPOW/pull/213#issuecomment-1219889216 .

EDIT: ~The fact that the ACTUAL value is ~1490 is ludicrous for a dihedral angle and _possibly_ suggests a problem with circvar because in principle it should have remained in the range -180 < x < +180.~ Looking at the code, the *reference value* is 1490.6576365537262. That's still suspicious and should be looked into. The docs for [scipy.stats.circvar()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.circvar.html) state that `0 ≤ circvar ≤ 1`, i.e., it is not clear how we can get 1490.6576365537262 _and_ pass the test!

It does not always fail for all CI runners, only some of them. There's no clear pattern with older/newer Python versions that I can discern. Locally (on macOS Python 3.8) the test always passes even while 3.8 fails in the CI.

1. We need to understand if this is a bug in the DihedralAnalysis code or in the testing.
2. We need to make the tests work reliably again.

**Comment by orbeckst** [comment]
@ALescoulie do you have _any_ idea what the issue could be here?

**Comment by orbeckst** [comment]
Note that the assertions
```python
        assert_almost_equal(self.DG48910_mean, dh1_mean, 6)
        assert_almost_equal(self.DG48910_var, dh1_var, 6)
        assert_almost_equal(self.DG491011_mean, dh2_mean, 6)
        assert_almost_equal(self.DG491011_var, dh2_var, 6)
```
should be switched around so that the reference values are in the second position: `assert_almost_equal(ACTUAL, DESIRED)`, which make the error diagnostics clearer.

Going forward, we could probably just use `assery pytest.approx(ACTUAL)  == DESIRED` for single float comparisons.

**Comment by ALescoulie** [comment]
I opened it in a debugger and can see that it is consistently failing that specific test at least on MacOs python 3.9, I'm not sure why thought. I could just get new recursion testing values since 1400 is pretty high

**Comment by orbeckst** [comment]
How did you calculate the reference value of 1490?

**Comment by ALescoulie** [comment]
I don't remember, I think I just ran circvar on it, but not sure, could just have been a mistake.

**Comment by orbeckst** [comment]
Can you recalculate it with the latest versions of numpy and python? Obviously, the reference value is important.

**Comment by ALescoulie** [comment]
i'll do that, and see if it works on the CI
