### ISSUE TITLE
need tests

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#23]
In the light of issue #20 we really need tests. That's not easy but we need to get started.

An example is an initial test in `mdpow/tests/test_fep.py`.

**Comment by orbeckst** [comment]
You're already making good progress!

**Comment by ianmkenney** [comment]
@orbeckst Does gromacswrapper have a way to suspend the script calling its functions until the process completes?

**Comment by orbeckst** [comment]
Not sure what you mean. By default the python process waits until the gromacs tool is done and has returned its output. 

Ultimately it uses subprocess.popen for calling gromacs tools. 



--
Oliver Beckstein
email: orbeckst@gmail.com


Am May 20, 2016 um 10:19 schrieb Ian Kenney <notifications@github.com>:

**Comment by ianmkenney** [comment]
Oh, well now that you say that, it seems I misinterpreted the output. Everything works as expected.

**Comment by orbeckst** [comment]
There are now minimal tests running  successfully on travis.

**Comment by orbeckst** [comment]
@ianmkenney focus on getting everything to work with Gromacs 4.6.6 and then we tackle Gromacs 5 #36.
