### ISSUE TITLE
Determine if scipy or pytest responsible for version-specific failure

### ISSUE THREAD

**Issue by cadeduckworth** [Becksteinlab/MDPOW#239]
https://github.com/Becksteinlab/MDPOW/blob/525f2cf09a88074442daf89eb070e327fa8d1eca/mdpow/tests/test_automated_dihedral_analysis.py#L178

**Comment by cadeduckworth** [comment]
This needs to be figured out for at least two existing tests in this module.

**Comment by cadeduckworth** [comment]
currently documented in the tests as:

`# the following 'reason' affects every downstream function that relies `
`# on the atom indices returned for dihedral atom group selections `
`# issue raised (#239) to identify and resolve exact package/version responsible `
`@pytest.mark.skipif(sys.version_info < (3, 8), reason='pytest=7.2.0, build=py37h89c1867_0, ' `
`                   'returns incorrect atom_indices for dihedral atom group selections')`
                       
*appears to be related to atom indices of dihedral atom group selections*

**Comment by orbeckst** [comment]
This issue will become moot with PR #249 (drop Python 3.7).
