### ISSUE TITLE
default names of output pdf files from mdpow-pow and mdpow-pcw

### ISSUE THREAD

**Issue by iorga** [Becksteinlab/MDPOW#25]
Currently mdpow-pow and mdpow-pcw scripts generate pdf files with default names `dVdl_UNK.pdf` and `dVdl_UNK_water`, respectively, assuming that the ligand code is UNK. I suggest that these names should be `dVdl_UNK_pow.pdf`and `dVdl_UNK_pcw.pdf`, respectively.

**Comment by iorga** [comment]
It seems that this issue was already solved by @orbeckst with the commit SHA: 62b01d651a353100e31be062285667683548f7c9.

Closing.

**Comment by orbeckst** [comment]
Funny that I anticipated your issue. Of course now it makes me doubly happy that I fixed it :-)
