### ISSUE TITLE
Use NPT by default for FEP

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#27]
Switch mdp files for fep to use Parrinello-Rahman p coupling.

**Comment by ianmkenney** [comment]
We also want the NPT to use Parrinello-Rahman as well, right? Instead of Berendsen...

**Comment by orbeckst** [comment]
Yes, let's do that. the MD_relax still uses Berendsen.

**Comment by ianmkenney** [comment]
I changed the MDPs in the templates directory to enable parrinello-rahman. SHA b3f09d2765a044db89f558e9c0be77d465cea14c

I will write these into tests

**Comment by orbeckst** [comment]
Did yoo do a manual test?

**Comment by ianmkenney** [comment]
Not yet, I can do it in about an hour

**Comment by ianmkenney** [comment]
``You are generating velocities so I am assuming you are equilibrating a
  system. You are using Parrinello-Rahman pressure coupling, but this can
  be unstable for equilibration. If your system crashes, try equilibrating
  first with Berendsen pressure coupling. If you are not equilibrating the
  system, you can probably ignore this warning.
``

I forgot about this. Do we really want to use Parrinello-Rahman here?

**Comment by orbeckst** [comment]
@ianmkenney as we discussed: Try to make it use the previous information by providing `grompp` with
```
grompp -t MD_relaxed.trr -e MD_relaxed.edr
```
and *switch off generation of new velocities in the MDP file* --- do the latter as part of the script (by passing the correct mdp options to `gromacs.setup.MD_setup()` instead of changing it in the template file). It's safer to keep the template MDP in a state where you can take it for manual simulations.

**Comment by orbeckst** [comment]
@iorga just so you know: @ianmkenney is working on the issue. The code is currently on the [feature-npt branch](https://github.com/Becksteinlab/MDPOW/tree/feature-npt).

(By mentioning you in this issue, you should now get updates.)

**Comment by orbeckst** [comment]
@ianmkenney what needs to be done to make this work?

**Comment by orbeckst** [comment]
@iorga : you can try this branch with
```
git fetch --all
git checkout -b feature-npt origin/feature-npt
```
Then check that you are on the *feature-npt* branch
```
git branch
```

If you install the package you should then use the MDP file with NPT enabled. You might have to increase the `maxwarn` for the NPT step because `grompp` is probably going to complain that you shouldn't start Parrinello-Rahman without equilibration.

You can always go back with
```
git branch develop
```

and switch again with
```
git branch feature-npt
```

**Comment by iorga** [comment]
Thanks @orbeckst for the detailed protocol, it worked without problems. I will use the newly installed version to run the validation simulations for octanol in water and octanol (there are no experimental values for Gsolv in cyclohexane or logPcw).

**Comment by ianmkenney** [comment]
Cross posting from #28 

One benzene ring is the solute for all of these simulations. The runinput can be found here runinput.yaml.txt (txt extension required by GitHub)

bar_opls.mdp was used for FEP windows; this mdp shows Pcoupl set to Parrinello-Rahman (other parameters needed for this are written in the git log). This is reflected in the log files from the windows themselves.

The pressures can be found here. These were generated with g_energy -f md.edr using the pressure option.
pressures.txt

I have every step of this project scripted, so if we need more data, that's not a problem.
