### ISSUE TITLE
Simulation stages cannot be restarted in case of an error

### ISSUE THREAD

**Issue by a-ws-m** [Becksteinlab/MDPOW#272]
`mdpow.restart.start()` raises a `JournalSequenceError` if there is any incomplete stage, even if the stage that you are trying to start is the incomplete one:
```
JournalSequenceError: Cannot start stage MD_NPT because previously started stage MD_NPT has not been completed.
```
I think the check should pass if `stage == self.current`, as well.

**Comment by orbeckst** [comment]
Yes, that sounds like a logic error in the code.
