### ISSUE TITLE
Use Parrinello-Rahman pressure coupling in MD_NPT

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#28]
Change the pressure coupling algorithm in the MD_NPT protocol from Berendsen to Parrinello-Rahman. Requires:

- [x] Change Pcoupl from Berendsen to Parrinello-Rahman in NPT_opls.mdp
- [x] Pass '-t $previous_checkpoint' to GromacsWrapper via MDPOW setupMD function
- [x] Run benzene simulations

**Comment by ianmkenney** [comment]
@orbeckst Should I just include a maxwarn in runinput.yaml to get around the warning about using parrinello-rahman for equilibration? I can just remove gen_vel from the mdp to resolve the error (which I don't think is something we should do). Any suggestions?

**Comment by ianmkenney** [comment]
Well we do maxwarn: 1 in FEP, so I see no reason not to do it in MD_NPT. Nevermind then. I am running the benzene simulations now.

**Comment by orbeckst** [comment]
Removing genvel is the correct solution because velocities should be taken from the cpt file. 

If I misunderstood and we don't have a cpt file to start with then increase maxwarn. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Mar 9, 2016 um 13:55 schrieb Ian Kenney <notifications@github.com>:

**Comment by orbeckst** [comment]
@iorga noticed that you also need to update `bar_opls.mdp`.

**Comment by ianmkenney** [comment]
I have updated the bar_opls.mdp along with removing genvel in NPT_opls.mdp.

 Path to simulations: ` /nfs/homes/ikenney/Projects/solvation_free_energy/MDPOW/feature-NPT-testing/reproducibility `

I finished the three trial runs across each solvent. The results are below in kJ/mol. I will find the experimental values later today and post them in a comment.

| Run # | Cyclohexane     | Water              | Octanol         |
|-------|-----------------|--------------------|-----------------|
| 1     | -16.1197 (0.22) | 0.24442 (0.20)     | -14.6315 (0.35) |
| 2     | -16.5359 (0.21) | 0.566847 (0.20)    | -14.8189 (0.35) |
| 3     | -15.8721 (0.21) | -0.00973051 (0.20) | -15.3112 (0.37) |

**Comment by orbeckst** [comment]
That's benzene, right? How long were the FEP windows? Can you attach your `runinput.yml` to this issue?

**Comment by orbeckst** [comment]
Please also manually check in the FEP mdp and log files that we are really using P-R during the simulations. Please report the average pressure +/- stdev for, say the Coulomb lambda=0, VDW lambda=0, 0.5, 1.0 windows. (Just grep from the summary in the log file.)

**Comment by orbeckst** [comment]
This discussion really belongs to #27... am I right in that the FEP windows were also run with P-R?

**Comment by ianmkenney** [comment]
One benzene ring is the solute for all of these simulations. The runinput can be found here [runinput.yaml.txt](https://github.com/Becksteinlab/MDPOW/files/176984/runinput.yaml.txt) (txt extension required by GitHub)

bar_opls.mdp was used for FEP windows; this mdp shows Pcoupl set to Parrinello-Rahman (other parameters needed for this are written in the git log). This is reflected in the log files from the windows themselves.

The pressures can be found here. These were generated with `g_energy -f md.edr` using the pressure option.
[pressures.txt](https://github.com/Becksteinlab/MDPOW/files/177051/pressures.txt)

I have every step of this project scripted, so if we need more data, that's not a problem.

**Comment by orbeckst** [comment]
Thanks. As just discussed, even though the average pressures range from -10... 10 bar this is probably correct. The small system size makes it hard to get accurate pressures. (When we compared to the NVT runs, we saw values on the order of 100 bar.)

Perhaps we need to check bigger water boxes (d = 1.5 nm instead of 1 nm) to get better average pressures.

**Comment by iorga** [comment]
Experimental solvation free energies for benzene (from MNSol-2012, in kcal/mol):
- water: -0.87
- octanol: -3.72
- cyclohexane: -4.19

**Comment by iorga** [comment]
Thanks @ianmkenney and @orbeckst for all this information.This is also related to the issue #27.

I have ran a few tests with the new `bar_opls.mdp` file, below is the overview for benzene. The first two lines were calculated with the old version of `bar_opls.mdp`, so it's NVT for FEP (and clearly not reproducible). The last two lines used the new version of `bar_opls.mdp`, so it's NPT for FEP. For the third I have also ran a new equilibrium simulation, whereas for the fourth I have repeated only the FEP sims, using the equilibrium simulation from the third. Good news, I can confirm Ian's results, in these conditions we are well reproducible. Considering Ian's three calculations and the (last) two of mine, we can even try to evaluate the variability of our predictions for repeated runs of the same compound.

```
water	3.42	0.20	7.55	0.06	-10.97	0.19	NPT+NVT
water	-3.15	0.19	7.55	0.06	-4.40	0.18	NPT+NVT
water	0.41	0.21	7.54	0.07	-7.94	0.20	NPT+NPT
water	-0.14	0.20	7.54	0.06	-7.40	0.19	(NPT)+NPT

octanol	-17.36	0.32	1.14	0.08	16.22	0.31	NPT+NVT
octanol	-14.29	0.42	1.90	0.13	12.39	0.39	NPT+NVT
octanol	-15.05	0.45	1.47	0.26	13.58	0.37	NPT+NPT
octanol	-14.67	0.35	1.54	0.12	13.13	0.33	(NPT)+NPT

cyclohexane	-15.16	0.23	0.21	0.01	14.95	0.23	NPT+NVT
cyclohexane	-15.87	0.21	0.21	0.01	15.65	0.21	NPT+NVT
cyclohexane	-16.13	0.22	0.20	0.01	15.93	0.22	NPT+NPT
cyclohexane	-16.39	0.21	0.21	0.01	16.19	0.21	(NPT)+NPT
```
