### ISSUE TITLE
one-shot do-all workflow script

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#33]
We want a solution to run the _whole protocol_ (or workflow) with a single command.

Possible approaches
- daemon/nanny process
- chains of Gridengine jobs
- ...

**Comment by ianmkenney** [comment]
I think this would be handled best using Firework at this point. I will check how easily it can be implemented in the MDPOW scripts.

**Comment by orbeckst** [comment]
+1 for [Fireworks](https://pythonhosted.org/FireWorks/)

**Comment by dotsdl** [comment]
Happy to help. It could even be a single function the output of which could be a ``Workflow`` object that a user can feed to their launchpad of choice.

**Comment by orbeckst** [comment]
The `mdpow-*` scripts
- `mdpow-equilibrium`
- `mdpow-fep`

are only thin option processors and use the functions in `mdpow.run`. They should be easily wrappable or at least it should be easily possible to decompose these functions into steps in a FW workflow.

The analysis scripts
- `mdpow-solvationenergy`
- `mdpow-pcw`
- `mdpow-pow`

should be refactored so that their analysis code also resides in `mdpow.run` (or elsewhere) and becomes easily accessible for FW.
