### ISSUE TITLE
Dynamic version calculation breaks clean installation

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#35]
Dynamic calculation of the version in setup.py circumvents the installation of a dependency (pyyaml) and causes an import error on `pip install -e`. I removed the offending line and hard coded in the version into setup.py...

@orbeckst do you have any preferences on how I fix this? I see that [`__init__.py`](https://github.com/Becksteinlab/MDPOW/blob/develop/mdpow/__init__.py)  has `import config` at the bottom (line 540) but is never used. This seems to be the only source of the error. Does this really need to be there?

Commit of hard code: 40cef6acdb009fcebd0563688ff80333ecbd4f16

**Comment by orbeckst** [comment]
Does dynamic version import work when you remove the `import config`?
If so, then that would be the preferred way.

**Comment by orbeckst** [comment]
Btw, when you change these things, work on a branch instead of develop. In this way it is easier to keep the history clean, for instance, if you now go back to doing dynamic versioning in `setup.py`.

**Comment by orbeckst** [comment]
Fixed in b19bcc244014101dfb5ffef6f8c009198ae4d43e
