### ISSUE TITLE
Minimum distance default leads to instabilities

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#37]
I have been running some some manual and scripted solvation free energy calculations on benzene in water and have found that the default value of 1nm leads to many failed simulations. 

`Fatal error: The box size in direction X (2.449481) times the triclinic skew factor (0.816497) is too small for a cut-off of 1.000000 with 2 domain decomposition cells, use 1 or more than 2 cells or increase the box size in this direction`

Should we really be setting 1nm to the default?

**Comment by ianmkenney** [comment]
@orbeckst Any thoughts?

**Comment by orbeckst** [comment]
One can run on fewer cores or use particle decomposition (`-pd` in Gromacs 4.6.x – is this still supported in 5.x?). It's a general problem with small boxes.
Benzene is pretty small so that will lead to the smallest boxes.

However, we can easily increase the min distance to 1.2 nm – try that.

**Comment by orbeckst** [comment]
You changed the default in d164fe2aa3b83e766b8e81e15b6f8a0363e6aae2.

**Comment by orbeckst** [comment]
I cherry-picked d164fe2 onto develop as 03d50033daf467491b3c6daf5f2ea143754e3ed7.

**Comment by orbeckst** [comment]
For the 0.6.0 release #4  I reverted to 1.0 nm  (see b0e3b1895b4c889e3b3d536fc458a8ab88a76e08). @iorga requested this change for consistency with the SAMPL5 runs.

After the release we should revisit this issue.

**Comment by iorga** [comment]
We need to run the simulations using the M24 modification of TIP3P water (#46) with the same parameters as before, then we can revert the min distance to 1.2 nm.

**Comment by orbeckst** [comment]
> On 7 Aug, 2016, at 13:08, Bogdan I. Iorga <notifications@github.com> wrote:
> 
> We need to run the simulations using the M24 modification of TIP3P water (#46) with the same parameters as before, then we can revert the min distance to 1.2 nm.

Ok. 

I think there's a way to set the distance in the cfg file but for right now we'll leave the default.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by orbeckst** [comment]
I think we will leave the default at 1 nm for the time being; we also set the number of cores to 3 in PR #77 in order for the tests with 1 nm to pass. Ultimately, the user has to make a decision for these values. We have done all the SAMPL work with 1 nm for the water. If we get results that indicate that we should rather use 1.2 nm then we change the default.
