### ISSUE TITLE
install gromacs on travis

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#41]
CI on travis is now running (#24) but for integration tests (part of #23) we need a working [Gromacs](http://www.gromacs.org) installation.

We would like to test at least:

- [x] Gromacs 4.6.6
- [x] Gromacs 5.1.2

See also Becksteinlab/GromacsWrapper#39 – any solution from GromacsWrapper can be applied here.

**Comment by ianmkenney** [comment]
We currently have gromacs installed on travis, but it is through Acellera ( mentioned by @dotsdl ) . I am thinking it might just be easier to do a quick and dirty install with the shipped fft libraries. Is this the right way to go?

**Comment by dotsdl** [comment]
@ianmkenney maybe, but good luck. I think the shortest path to victory here with gromacs 5.x at least is to use the gromacs build installed through conda (from the acellera channel). It should *just work*, in that with the conda env active the ``gmx`` binary should be in the path. Does GromacsWrapper not find it on Travis? I'm too busy to look myself now, but just wanted to chime in.

**Comment by orbeckst** [comment]
Using acellera conda is fine for the time being. Are there any limitations that we face?

Almost certainly faster than compiling.

We should actually build our own condo gromacs packages… but I am happy to do this once everything else is working.

> On 30 May, 2016, at 12:23, Ian Kenney <notifications@github.com> wrote:
> 
> We currently have gromacs installed on travis, but it is through Acellera ( mentioned by @dotsdl ) . I am thinking it might just be easier to do a quick and dirty install with the shipped fft libraries. Is this the right way to go?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by ianmkenney** [comment]
Alright, I was just wondering. I am probably just unfamiliar with Acellera. I will figure out how to get 4.6.6 using it.

**Comment by orbeckst** [comment]
> On 30 May, 2016, at 12:40, Ian Kenney <notifications@github.com> wrote:
> 
> Alright, I was just wondering. I am probably just unfamiliar with Acellera. I will figure out how to get 4.6.6 using it.

If it’s not in their channel then you cannot get it.

But it DOES exist as a Ubuntu package so just install it through travis. That’s even faster.

You just need some logic to do one or the other and then source the correct GMXRC. But all of it is possible with travis matrix builds. Have a look at the MDAnalysis .travis.yml file.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by ianmkenney** [comment]
it looks like the version of gromacs on the repos is 4.5.5 instead of 4.6.6. Is there a way to get a different version or do we just use the repo version (I take it that the changes between these versions will be very significant).

**Comment by orbeckst** [comment]
> On 30 May, 2016, at 15:48, Ian Kenney <notifications@github.com> wrote:
> 
> it looks like the version of gromacs on the repos is 4.5.5 instead of 4.6.6. Is there a way to get a different version or do we just use the repo version (I take it that the changes between these versions will be very significant).

4.5.5 is very old. I don’t think that this will work with MDPOW.

In Ubuntu it is possible to get packages from other repositories. Maybe there’s one available. Search?

Building conda packages looks more and more appealing every minute because then at least we know exactly what we have. The only issue is that you need to build it in a VM with pretty old Linux version (such as old Cent OS). I don’t know the details, though.

**Comment by orbeckst** [comment]
Maybe there are travis settings that allow you to use a newer [Ubuntu releases](https://wiki.ubuntu.com/Releases)
```yaml
      sudo: true
      dist: trusty
```

Check travis docs.

**Comment by ianmkenney** [comment]
@orbeckst it looks like in https://travis-ci.org/Becksteinlab/MDPOW/builds/143638576 we are getting an error with a pip install for `recsql`. This comes from creating the conda environment defined in `environment.yml`. We didn't have this issue before did we?

**Comment by ianmkenney** [comment]
Funny enough, I was able to pip install in the continuumio/miniconda docker container. The only difference I see is that travis downloaded a tarball while the container download a `.whl`. Does this different behavior make sense to you?

**Comment by ianmkenney** [comment]
Nevermind, it worked on my second push... it downloaded the .whl on travis this time and worked.

**Comment by ianmkenney** [comment]
Currently in travis we are creating a single env called `mdpow_test`. Do we want to have both versions of gromacs installed and used under this env? I assume we are planning to source one and then the other for testing.

**Comment by orbeckst** [comment]
Separately, not in the same env but as a test matrix. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
Closed with PR #44.
