### ISSUE TITLE
Packaging files for use in tests

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#48]
Need an efficient way of packaging states of an MDPOW workflow to be used as intermediate points in testing.

For instance, if testing the the MD_NPT protocol, one would need to start just after the emin protocol. However, we need to keep all tests independent of each other; using the files from previous tests break that rule. Is the following setup really the best:
```
+ --- /testing_resources/states
       + --- Emin
               + --- Solvation
       + --- MD_NPT
               + --- Solvation --> Emin 
       + --- FEP
               + --- Solvation --> Emin --> MD_NPT
       + --- Analysis
               + --- Solvation --> Emin --> MD_NPT --> FEP
```

This also raises the question involving trajectories that will be used for analysis. Do we just use shorter trajectories?

**Comment by ianmkenney** [comment]
@orbeckst Do you know of any solutions or should we just bite the bullet?

**Comment by orbeckst** [comment]
Use short trajectories. Maybe tar/bzip the tree in the state that you need and then unpack for testing?

I don't see a very nice option.

But remember that you only have to run enough code to test that it works – it does not have to produce converged results.

**Comment by orbeckst** [comment]
As we discussed, perhaps the best way to build snapshots is to create a clean working environment and run the desired simulation.

- version control each step (keep trajectories short); commit/tag each step
- write "manifest files" (yml) that describe which files to pick in order to create a given state

**Comment by orbeckst** [comment]
Done with `manifest`.
