### ISSUE TITLE
coverage should not contain the tests

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#49]
PR #39 adds testing with Gromacs 4 and Gromacs 5 (yay!). However, coverage also analyses coverage of the tests themselves. That's not helpful. All tests ought to be excluded from coverage reporting.

There should be some simple settings for `coverage` in the travis.yml file that exclude tests.

**Comment by orbeckst** [comment]
I was not able to find anything in the rather sparse [docs for pytest-cov](http://pytest-cov.readthedocs.io/en/latest/) (which we are using) or the related [coverage docs](https://coverage.readthedocs.io/en/latest/index.html). 

@dotsdl any ideas?

For example output see, for instance, https://travis-ci.org/Becksteinlab/MDPOW/jobs/150184380.

**Comment by orbeckst** [comment]
@ianmkenney can you please find out how to fix coverage so that they do not contain the tests?

**Comment by ianmkenney** [comment]
Sure thing

**Comment by dotsdl** [comment]
See how we do this for `datreant.core`: https://github.com/datreant/datreant.core/blob/develop/.coveragerc

**Comment by ianmkenney** [comment]
For future reference: http://coverage.readthedocs.io/en/coverage-4.1/config.html

**Comment by ianmkenney** [comment]
@orbeckst I have a new PR for codecov. My addition of `.coveragerc` (thanks @dotsdl ) fixed the problem. Some of the options listed in the docs might be interesting to add though, so I will leave it open for another few days while I look at our options.
