### ISSUE TITLE
Simulations use absolute paths for file paths

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#59]
@orbeckst currently the simulation files are using absolute paths to identify structure files. While writing tests (pr #58 ) I have been having trouble dealing with the previously generated files having paths related to where they were created; the tests will fail even though all required files are there. I know of the rebuild simulation script, but is that the only solution to this problem? It seems to me that having the abspaths is just an unnecessary restraint.

**Comment by orbeckst** [comment]
Abs paths were considered the safer option at the time. Wit relative paths you rely on the pickle file always being in the same place and all the directory hopping seemed more dangerous. 

But you could probably make relative paths work too, especially given that we specify everything in the cfg file as relative paths. 

I would start getting the tests to run with abspaths and abusing the rebuild script. Once this works, we can try relative paths. 

Probably even better would be using datreant (@dldotson) but that's the future...

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
I think for right now we left it at absolute paths but tests use `simulation.make_paths_relative()`.

Please re-open if necessary.
