### ISSUE TITLE
Remove MDrunnerSimple from fep.py

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#60]
The current implementation of MDrunnerSimple really doesn't add very much to what is provided with `gromacs.run.MDrunner`. 

``` python
class MDrunnerSimple(gromacs.run.MDrunner):
    """Gromacs mdrun.

    Use Gromacs 4.5.x with threaded mdrun to get max performance and
    just leave everything as it is. For older version you can change
    the name and add a mpiexec binary to launch a multiprocessor
    job. See :mod:`gromacs.run` for details.

    """
    mdrun = "mdrun"
    mpiexec = None
```
- [x] remove `MDrunnerSimple` from MDPOW
- [x] switch all instantiations of `MDrunnerSimple` to instantiations of `gromacs.run.MDrunner`

**Comment by orbeckst** [comment]
(This is needed to make it work with Gromacs 5.1.x #36.)

**Comment by orbeckst** [comment]
I think this was done in 9fb7a8aa5368c8f715a508f2917d2297539f22f2 but commit did not auto-close this issue.
