### ISSUE TITLE
manifest_parser name change will break test functionality

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#63]
manifest_parser name change will break test functionality. Preemptive changes should include:
- [ ] change all imports (i.e. `import manifest` --> `import pybol` )
- [ ] change all instantiations of Manifest objects (i.e. `m = manifest.Manifest()` --> `m = pybol.Manifest()`
- [ ] change how travis installs pybol

**Comment by orbeckst** [comment]
Is this fixed?

**Comment by ianmkenney** [comment]
It shouldn't be a problem just yet, I have to change them both at the 
same time basically. That will be happening this weekend.

**Comment by ianmkenney** [comment]
scratch that, I see that there is a problem, I will look into it

**Comment by orbeckst** [comment]
Is this fixed with PR #67 ?

**Comment by orbeckst** [comment]
ping @ianmkenney – please review this issue and close if solved otherwise say what needs to be done.

**Comment by orbeckst** [comment]
ping @ianmkenney

**Comment by orbeckst** [comment]
ping @ianmkenney – please review this issue and close if solved otherwise say what needs to be done.

**Comment by orbeckst** [comment]
@ianmkenney, I am assuming that this was done and is good because pybol has been in use for the tests for a while.
