### ISSUE TITLE
Add EDR/(Compressed XVG) switch for dH data output

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#70]
Add an option in the `runinput.yml` file for the user to specify how they would like energy data to be written out. The options should be between zipped `xvg` files and an `edr` file

**Comment by ianmkenney** [comment]
@orbeckst Do we want the default to be compressed XVGs or EDRs? I assume that EDR should be default, since it contains information that applies to all methods, while XVGs only apply to BAR and TI.

**Comment by orbeckst** [comment]
EDR as default. We will also want a helper script that can generate compressed XVGs from the EDR so that we are backwards compatible. 

We will either write EDR or XVG but not both. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by ianmkenney** [comment]
@orbeckst it seems that EDRs were produced by default alongside the bzipped xvgs the whole time. You can see that here:
```
ikenney @ ********** : ~/mdpow_tutorial_manual/FEP/water/VDW/1000
10:00 AM >>> ls
local.sh  md.cpt  md.edr  md.gro  md.log  md.mdp  mdout.mdp  md.tpr  md.trr  md.xtc  md.xvg.bz2  processed.top
```
According to the log:
```
ikenney @ ********** : ~/mdpow_tutorial_manual
10:02 AM >>> cat mdpow.log | grep grompp | tail -n 1
2016-11-08 12:20:10,182 gromacs.core DEBUG    gmx grompp -c /nfs/homes/ikenney/mdpow_tutorial_manual/MD_NPT/md.gro -f md.mdp -pp processed.top -o md.tpr -n /nfs/homes/ikenney/mdpow_tutorial_manual/solvation/main.ndx -p /nfs/homes/ikenney/mdpow_tutorial_manual/top/pp_system.top -maxwarn 1
```
This also shows up in previous runs:
```
ikenney @ ********** : ~/Projects/solvation_free_energy/MDPOW/feature-NPT-testing/reproducibility/run1/benzene/FEP/water/VDW/0050
10:04 AM >>> ls
md.cpt  md.edr  md.log  md.mdp  mdout.mdp  md.pdb  md_prev.cpt  md.tpr  md.trr  md.xtc  md.xvg.bz2  processed.top  wsq_4_MDPOW_array_default_466_pd.sge
```
Same with its log:
```
ikenney @ ********** : ~/Projects/solvation_free_energy/MDPOW/feature-NPT-testing/reproducibility/run1
10:05 AM >>> cat mdpow.log | grep grompp | tail -n 1
2016-03-15 11:31:44,029 gromacs.core DEBUG    grompp -c /nfs/homes/ikenney/Projects/solvation_free_energy/MDPOW/feature-NPT-testing/reproducibility/run1/benzene/Equilibrium/octanol/MD_NPT/md.pdb -f md.mdp -pp processed.top -o md.tpr -n /nfs/homes/ikenney/Projects/solvation_free_energy/MDPOW/feature-NPT-testing/reproducibility/run1/benzene/Equilibrium/octanol/solvation/main.ndx -p /nfs/homes/ikenney/Projects/solvation_free_energy/MDPOW/feature-NPT-testing/reproducibility/run1/benzene/Equilibrium/octanol/top/pp_system.top -maxwarn 1

```


Is there a way to omit the creation of `edr` files in `grompp`?

**Comment by ianmkenney** [comment]
It looks like we can use the `separate-dhdl-file` mdp option, which should simplify a lot. See the [4.6.6 manual](http://manual.gromacs.org/archive/4.6.6/online/mdp_opt.html) as well as the [most recent manual](http://manual.gromacs.org/online/mdp_opt.html). This seems like it's the only option that needs to be considered. Thoughts?

**Comment by orbeckst** [comment]
> it seems that EDRs were produced by default alongside the bzipped xvgs the whole time. 

I am not sure that these EDR files actually contain the data we need unless you set the right flags. 

> Is there a way to omit the creation of edr files in grompp?

I suppose you can set the output frequency in the MDP file to zero.

**Comment by orbeckst** [comment]
From recent discussion: also need to set in [mdp](http://manual.gromacs.org/online/mdp_opt.html)
```
calc-lambda-neighbors  = -1  ; calculate ALL possible foreign lambdas
separate-dhdl-file = no      ; write to EDR file instead of XVG
```

@rhheilma – please note that you also need the `calc-lambda-neighbors  = -1` for manual tests with MBAR #26.
