### ISSUE TITLE
MDP should use `init_lambda_state` and full vector of `fep_lambdas`

### ISSUE THREAD

**Issue by dotsdl** [Becksteinlab/MDPOW#76]
Currently, the MDP files generated by MDPOW use the `init_lambda` MDP option to specify the value of lambda for the window, and other windows in the run may or may not be listed in the `fep_lambdas` vector. This presents a problem with the resulting EDR files if estimators like `MBAR` are to be used, since only values of `DH_lambda` are recorded for the windows listed in `fep_lambdas`.

Instead of this, we should probably list all windows for each MDP file in the `fep_lambda` vector, then indicate which window we are simulating using the `init_lambda_state` option instead of using `init_lambda`. This appears to be the recommendation of the current [gromacs docs](http://manual.gromacs.org/documentation/5.1.4/user-guide/mdp-options.html#mdp-init-lambda-state) as well.

**Comment by orbeckst** [comment]
@ianmkenney please work on this blocking issue so that @rhheilma can continue work on #26.

**Comment by orbeckst** [comment]
This will be fixed as part of #75 but tests for actual FEP calculations are still missing, see https://github.com/Becksteinlab/MDPOW/pull/75#issuecomment-271737098.

**Comment by orbeckst** [comment]
@dotsdl / @ianmkenney : does `fep_lambdas` work with the [MDP FEP options](http://manual.gromacs.org/online/mdp_opt.html#free) that we are using for solvation free energy calculations:
- `couple-moltype`
- `couple-lambda0`
- `couple-lambda1`
- `couple-intramol`

**Comment by orbeckst** [comment]
I merged PR #75 but develop needs to be tested now!

**Comment by orbeckst** [comment]
@VOD555 do you have any idea how we're dealing with `init_lambda_state` and `fep_lambdas` at the moment?

- Can this issue be closed?
- Do we need tests?

**Comment by VOD555** [comment]
@orbeckst 
1. Yes, we've already been using init_lambda_state and a list of all window lambdas were used as input for fep_lambdas.
2. In principle mbar calculations could not be performed if the edr file doesn't contain information with other lambdas. We have testes using mbar, so I think we don't need tests for this one.

**Comment by orbeckst** [comment]
Then we can close. Thank you.
