### ISSUE TITLE
fep.py: array comparison fails for a list of lambdas

### ISSUE THREAD

**Issue by rhheilma** [Becksteinlab/MDPOW#78]
When running:
```python
gwat.setup(...)
``` 
an `IndexError` is raised due code of the form 
```python
numpy.where([0,0.5,0.75,1] == current_lambda)[0][0]
```
The offending line is 625 in `fep.py`. A quick fix for this problem is to cast the list being compared to the current lambda as a numpy array.

**Comment by ianmkenney** [comment]
The tests likely failed to catch the error because when we load the FEP schedule from a file we use use the `getarray` method while our default values (which Ryan was using) are lists. A test has not been written yet that uses these values from what I can see.
