### ISSUE TITLE
Solvationenergy script does not play well with new EDR outputs

### ISSUE THREAD

**Issue by ianmkenney** [Becksteinlab/MDPOW#82]
The implementation of EDRs as the new default for energy format did not take into account that the solvationenergy script will not work. A quick workaround to this issue would be to go through all of the FEP directories and run `gmx energy -f md.edr -s md.tpr -odh md.xvg` in order to extract the relevant information.

**Comment by orbeckst** [comment]
@iorga reported that the workaround failed:

> The conversion works well, but it gives an error at the analysis step (see at the end of the message the output for the last conversion and for the analysis, with the error). The reason is the different format of the .xvg file. The old format (that used to work) has only three columns for the data, whereas the new one has 11 columns. I've used Gromacs 4.6 for the conversion, but I made a test with 5.1.3 and I get the same result.

We need to fix this properly.

**Comment by iorga** [comment]
@orbeckst @ianmkenney :

Example file _VDW/1000/md.xvg_ generated directly with _mdrun_, compatible with the script for analysis (simulation of compound V92 in TIP3P water):

```
# This file was created Sat Jul  2 05:45:03 2016
# by the following command:
# /sge/packs/packs_centos/opt/gromacs-4.6.5-centos6/bin/mdrun -nice 0 -pd -deffnm md -s md.tpr -c md.pdb -cpi -append -dhdl 
#
# mdrun is part of G R O M A C S:
#
# Green Red Orange Magenta Azure Cyan Skyblue
#
@    title "dH/d\xl\f{} and \xD\f{}H"
@    xaxis  label "Time (ps)"
@    yaxis  label "dH/d\xl\f{} and \xD\f{}H (kJ/mol [\xl\f{}]\S-1\N)"
@TYPE xy
@ subtitle "T = 300 (K) \xl\f{} = 1.0000"
@ view 0.15, 0.15, 0.75, 0.85
@ legend on
@ legend box on
@ legend loctype view
@ legend 0.78, 0.8
@ legend length 2
@ s0 legend "dH/d\xl\f{} \xl\f{} 1.0000"
@ s1 legend "\xD\f{}H \xl\f{} 0.9500"
0.0000 39.337975 -1.9606847
0.1000 36.981056 -1.8243572
...
4999.9000 16.345339 -0.56025125
5000.0000 17.454916 -0.61959253
```

Example file _VDW/1000/md.xvg_ generated with _gmx energy_ from _md.edr_, incompatible with the script for analysis (simulation of compound V92 in TIP4P-D water):

```
# This file was created Thu Feb 16 21:17:18 2017
# by the following command:
# g_energy -f md.edr -s md.tpr -odh md.xvg 
#
# g_energy is part of G R O M A C S:
#
# Giving Russians Opium May Alter Current Situation
#
@    title "dH/d\xl\f{} and \xD\f{}H"
@    xaxis  label "Time (ps)"
@    yaxis  label "dH/d\xl\f{} and \xD\f{}H (kJ/mol [\xl\f{}]\S-1\N)"
@TYPE xy
@ subtitle "T = 300 (K) \xl\f{} state 15: fep-lambda = 1.0000"
@ view 0.15, 0.15, 0.75, 0.85
@ legend on
@ legend box on
@ legend loctype view
@ legend 0.78, 0.8
@ legend length 2
@ s0 legend "dH/d\xl\f{} fep-lambda = 1.0000"
@ s1 legend "\xD\f{}H \xl\f{} to 0.0000"
@ s2 legend "\xD\f{}H \xl\f{} to 0.0500"
@ s3 legend "\xD\f{}H \xl\f{} to 0.1000"
@ s4 legend "\xD\f{}H \xl\f{} to 0.2000"
@ s5 legend "\xD\f{}H \xl\f{} to 0.3000"
@ s6 legend "\xD\f{}H \xl\f{} to 0.4000"
@ s7 legend "\xD\f{}H \xl\f{} to 0.5000"
@ s8 legend "\xD\f{}H \xl\f{} to 0.6000"
@ s9 legend "\xD\f{}H \xl\f{} to 0.6500"
@ s10 legend "\xD\f{}H \xl\f{} to 0.7000"
@ s11 legend "\xD\f{}H \xl\f{} to 0.7500"
@ s12 legend "\xD\f{}H \xl\f{} to 0.8000"
@ s13 legend "\xD\f{}H \xl\f{} to 0.8500"
@ s14 legend "\xD\f{}H \xl\f{} to 0.9000"
@ s15 legend "\xD\f{}H \xl\f{} to 0.9500"
@ s16 legend "\xD\f{}H \xl\f{} to 1.0000"
@ s17 legend "pV (kJ/mol)"
0.0000  53.072094 -46.998859 -45.491169 -43.791912 -39.933575 -35.609890 -30.953505 -26.060745 -21.002615 -18.428658 -15.832104 -13.217587 -10.589133 -7.9502602 -5.3040423 -2.6531689 0.0000000 0.60046887
0.1000  51.174484 -13.830273 -20.959404 -25.227877 -28.808428 -28.693056 -26.577942 -23.289324 -19.276548 -17.085632 -14.803619 -12.448470 -10.034684 -7.5740685 -5.0763111 -2.5494053 0.0000000 0.59744871
...
4999.9000  5.7709231 3117245.2 14020.708 4307.5537 1136.8596 456.98096 212.19237 102.78954 48.603519 32.398277 20.805849 12.618670 6.9878459 3.3034301 1.1187781 0.10136326 0.0000000 0.58023351
5000.0000  -1.1580856 3227388.8 12024.619 4129.1416 1213.2207 512.42627 245.05830 121.58544 59.078278 40.095535 26.366875 16.536850 9.6446648 4.9954109 2.0776262 0.50902510 0.0000000 0.57737970
```

**Comment by orbeckst** [comment]
The problems are mdpow.fep:[L839](https://github.com/Becksteinlab/MDPOW/blob/develop/mdpow/fep.py#L839) and mdpow.fep:[L840](https://github.com/Becksteinlab/MDPOW/blob/develop/mdpow/fep.py#L840) where we use the special computed attributes `XVG.error` and `XVG.tc`: they try to compute correlation time (and error of the mean, using tc) over *all* data columns. If one of the columns is 0 (as always for MBAR data) then the calculation of the correlation time returns 0 or an empty intermediate array. This crashes the calculation with 
```
IndexError: index -1 is out of bounds for axis 0 with size 0
```
in numkit.

Additionally, we are doing the costly tc/error calculation for all columns in the datafile but then only use the 0-th data column.

Solution:
```python
ncorrel = 25000  # aim for ≤ 25,000 samples for t_correl
nstep = int(numpy.ceil(len(x.array[0])/float(ncorrel))
tc_data = [numkit.timeseries.tcorrel(x.array[0], x.array[1], nstep=nstep) for x in xvgs]
DY = np.array([tc['error'] for tc in tc_data])
tc = np.array([tc['tc'] for tc in tc_data])
```

**Comment by orbeckst** [comment]
Implementing the fix is not a hold up, I started it, but implementing the test cases is because we don't have any FEP data files yet.

I would like to use @ianmkenney 's `alchemtest.gmx` data set but to test MDPOW we also need the `Gsolv.fep` pickle file. I regenerated data but if @ianmkenney still has his `Gsolv.fep` I could try to mash alchemtest and that file together.

I generated

**Comment by orbeckst** [comment]
@iorga this should work again. 

There's also a new method `Gsolv.convert_edr()` that generates all the necessary xvg files. I still need to add the conversion to the workflow, though.
