### ISSUE TITLE
support Python 3

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#84]
Support Python 2.7 and Python 3.6+ 

- [x] use `from __future__ import print_function, ...`
- [x] use `six` where necessary
- [x] add Python 3 tests to test matrix

**Comment by orbeckst** [comment]
Unless someone wants to put the effort into porting with `six` we will just keep it Python 2.7 and a stable set of dependencies.

**Comment by orbeckst** [comment]
@ALescoulie if you want to take the py3 upgrade on — _please_ do!!!!

**Comment by VOD555** [comment]
We need to replace `optparse` with 'argparse' in the scripts. 
`mdpow-solvationenergy`, `mdpow-pow` and `mdpow-pcw` have been changed to use `argparse`. 
We still need to do the same things in the others.

**Comment by orbeckst** [comment]
Accidentally closed with a premature merge.
