### ISSUE TITLE
New GROMACS user

### ISSUE THREAD

**Issue by chloell** [Becksteinlab/MDPOW#96]
Hello,

I have just installed GROMACS with the intention to use the MDPOW package.  I am going through the tutorial for MDPOW and am running into the following error:
"
```
gromacs.run : INFO     mdrun -cpi -stepout 1000 -deffnm md -v -append -nice 19

You can use the following GROMACS-specific command-line flags
to control the behavior of the tests:

SYNOPSIS

mdrun [-[no]h] [-src-root <string>] [-ref-data <enum>] [-nt <int>]
      [-nt_omp <int>] [-[no]delete-temporary-files]

OPTIONS

Other options:

 -[no]h                     (no)
           Print GROMACS-specific unit test options
 -src-root <string>
           Override source tree location (for data files)
 -ref-data <enum>           (check)
           Operation mode for tests that use reference data: check, create,
           update
 -nt     <int>              (1)
           Number of thread-MPI threads/ranks for child mdrun calls
 -nt_omp <int>              (1)
           Number of OpenMP threads for child mdrun calls
 -[no]delete-temporary-files (yes)
           At the end of each test case, delete temporary and output files


-------------------------------------------------------
Program:     mdrun, VERSION 5.1.4
Source file: src/gromacs/commandline/cmdlineparser.cpp (line 234)
Function:    void gmx::CommandLineParser::parse(int*, char**)

Error in user input:
Invalid command-line options
    Unknown command-line option -cpi
    Unknown command-line option -stepout
    Unknown command-line option -deffnm
    Unknown command-line option -v
    Unknown command-line option -append
    Unknown command-line option -nice

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
gromacs.run : CRITICAL Failure in MDrun, returncode = 1
gromacs.run : ERROR    run_check: mdrun failed to complete run
mdpow.run   : CRITICAL Failed MD_relaxed, investigate manually.
```
"

From tutorials I have watched on YouTube regarding the new GROMACS version, it seems that the issue is that I need to execute "gmx mdrun" instead of simply "mdrun".  Where/which are the files that I would need to change in order to accomplish this?  Running "gmx mdrun -cpi -stepout 1000 -deffnm md -v -append -nice 19" in the terminal command line worked, but if I am just using the mdpow scripts, it is still not working.

Thank you for your help,
Chloe

**Comment by orbeckst** [comment]
Hi @chloell , sorry, I hadn't monitored the issue tracker closely enough over the last few days.

Can you paste the code that you've been running?

In principle, GromacsWrapper knows when to use `gmx mdrun`. Does the following work:
```python
import gromacs

gromacs.mdrun(h=True)
```
It should show the help, something like
```
                   :-) GROMACS - gmx mdrun, VERSION 5.1.2 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov  Herman J.C. Berendsen    Par Bjelkmar
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra   Sebastian Fritsch
  Gerrit Groenhof   Christoph Junghans   Anca Hamuraru    Vincent Hindriksen
 Dimitrios Karkoulis    Peter Kasson        Jiri Kraus      Carsten Kutzner
    Per Larsson      Justin A. Lemkul   Magnus Lundborg   Pieter Meulenhoff
   Erik Marklund      Teemu Murtola       Szilard Pall       Sander Pronk
   Roland Schulz     Alexey Shvetsov     Michael Shirts     Alfons Sijbers
   Peter Tieleman    Teemu Virolainen  Christian Wennberg    Maarten Wolf
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2015, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, VERSION 5.1.2
Executable:   /Users/oliver/Biop/Library/Gromacs/version/5.1.2/bin/gmx
Data prefix:  /Users/oliver/Biop/Library/Gromacs/version/5.1.2
Command line:
  gmx mdrun -h

SYNOPSIS

gmx mdrun [-s [<.tpr>]] [-cpi [<.cpt>]] [-table [<.xvg>]]
          [-tabletf [<.xvg>]] [-tablep [<.xvg>]] [-tableb [<.xvg>]]
          [-rerun [<.xtc/.trr/...>]] [-ei [<.edi>]] [-multidir [<dir> [...]]]
          [-membed [<.dat>]] [-mp [<.top>]] [-mn [<.ndx>]]
          [-o [<.trr/.cpt/...>]] [-x [<.xtc/.tng>]] [-cpo [<.cpt>]]
          [-c [<.gro/.g96/...>]] [-e [<.edr>]] [-g [<.log>]] [-dhdl [<.xvg>]]
          [-field [<.xvg>]] [-tpi [<.xvg>]] [-tpid [<.xvg>]] [-eo [<.xvg>]]
          [-devout [<.xvg>]] [-runav [<.xvg>]] [-px [<.xvg>]] [-pf [<.xvg>]]
          [-ro [<.xvg>]] [-ra [<.log>]] [-rs [<.log>]] [-rt [<.log>]]
          [-mtx [<.mtx>]] [-dn [<.ndx>]] [-if [<.xvg>]] [-swap [<.xvg>]]
          [-deffnm <string>] [-xvg <enum>] [-dd <vector>] [-ddorder <enum>]
          [-npme <int>] [-nt <int>] [-ntmpi <int>] [-ntomp <int>]
          [-ntomp_pme <int>] [-pin <enum>] [-pinoffset <int>]
          [-pinstride <int>] [-gpu_id <string>] [-[no]ddcheck] [-rdd <real>]
          [-rcon <real>] [-dlb <enum>] [-dds <real>] [-gcom <int>]
          [-nb <enum>] [-nstlist <int>] [-[no]tunepme] [-[no]v]
          [-[no]compact] [-pforce <real>] [-[no]reprod] [-cpt <real>]
          [-[no]cpnum] [-[no]append] [-nsteps <int>] [-maxh <real>]
          [-multi <int>] [-replex <int>] [-nex <int>] [-reseed <int>]

DESCRIPTION

gmx mdrun is the main computational chemistry engine within GROMACS.
Obviously, it performs Molecular Dynamics simulations, but it can also perform
...
```

**Comment by chloell** [comment]
@orbeckst 

When I run the following command:
`mdpow-equilibrium --solvent water benzene/benzene.yml`
I get the following error:
```
Program:     mdrun, VERSION 5.1.4
Source file: src/gromacs/commandline/cmdlineparser.cpp (line 234)
Function:    void gmx::CommandLineParser::parse(int*, char**)

Error in user input:
Invalid command-line options
    Unknown command-line option -cpi
    Unknown command-line option -stepout
    Unknown command-line option -deffnm
    Unknown command-line option -v
    Unknown command-line option -append
    Unknown command-line option -nice
```
I have attached the log file and example file that I am running:
[test.tar.gz](https://github.com/Becksteinlab/MDPOW/files/1753269/test.tar.gz)

Thank you for your help!
~Chloe
.

**Comment by orbeckst** [comment]
I think you have a binary called `mdrun` in your PATH. I am not sure what it is. The options imply that it has *something* to do with tests.  I think GromacsWrapper picks up your `mdrun` executable in favor of `gmx`.  (By default, GW tries to [autodetect your Gromacs installation](http://gromacswrapper.readthedocs.io/en/latest/gromacs/core/config.html#setting-up-the-environment) – having a wrong executable on the path might trick it.)

I am actually not sure how you managed to get past the energy minimization, which also uses `gmx mdrun`.  I have a few questions that might help clearing things up:

## Questions

* How did you install Gromacs?
* What is the output of
   ```bash
   which gmx
   which mdrun
   ```
* Have you sourced `GMXRC` (or did a `module load ...` or similar) to make sure that Gromacs directories occur early on `PATH`? 
* What is the output of
  ```python
  import gromacs
  gromacs.mdrun(h=True)
  print(gromacs.mdrun.driver)
  ```
 
## More logging
You can also [instruct GW to immediately write a log file](http://gromacswrapper.readthedocs.io/en/latest/gromacs/init.html#logging) (`gromacs.log` by default):
```bash
export GW_START_LOGGING=True
mdpow-equilibrium --solvent water benzene/benzene.yml
```
should produce a `gromacs.log` file, too, that shows the very first things that are happening, even before MDPOW starts its own logger (which captures GW's output).  Look at the first ~15 lines or so (paste output `head -n 15 gromacs.log` if you need some help in understanding it). 

## Configuring GW

If you want to keep the `mdrun` file around then you can also [manually configure GromacsWrapper](http://gromacswrapper.readthedocs.io/en/latest/configuration.html) – I can help if you want to go down this route; something like
```ini
[Gromacs]
GMXRC = /usr/local/gromacs/bin/GMXRC
release = 5.1.4
tools = gmx
```
might work to make clear what you want to use (specify the correct path to `GMXRC`)

(Locally I am able to run the test case using the files that you attached; note that by default mdrun chooses the number of threads and

**Comment by orbeckst** [comment]
@chloell did any of the above suggestions help? If I don't hear anything else from you I will close this issue in a few days.

**Comment by chloell** [comment]
@orbeckst 

I haven't gotten a chance to try your suggestions, yet.  I will let you know as soon as I do, likely tomorrow.

Thank you!
I really appreciate your help,
Chloe

**Comment by chloell** [comment]
@orbeckst 

Thank you for your help!  The issue is solved.  We had installed the package on the Desktop; it is correctly installed, now.

Have a great day,
Chloe
