### ISSUE TITLE
support octanol/water mixtures

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#98]
Octanol phase typically contains some water. At the moment, only pure octanol solvation is supported.

The [SAMPL6 Part II logP instructions](https://github.com/MobleyLab/SAMPL6/blob/master/logP_challenge_instructions.md#possible-factors-to-consider-in-your-approach) mention 

> After mixing, the water and octanol phases may no longer be pure water and octanol. Please consider mutual solubility of water and octanol. Water and/or salts may be found in the octanol phase. Octanol may be found in the aqueous phase. The mole fraction of water in octanol was measured as 0.2705 ± 0.0028 at 25°C [7].
>
> [7] Lang, Brian E. “Solubility of Water in Octan-1-Ol from (275 to 369) K.” Journal of Chemical & Engineering Data 57, no. 8 (August 9, 2012): 2221–26. https://doi.org/10.1021/je3001427.

- [x] add octanol/water boxes for the condition above
- [ ] allow selection of octanol+water box instead of pure octanol

Even better would be a way to set the water/octanol mole fraction and generate the correct solvation environment on the fly.

**Comment by iorga** [comment]
About mutual solubility of water and 1-octanol (from https://pubs.acs.org/doi/full/10.1021/acsomega.7b01102):
- the solubility of octanol in water is very low
- the equilibrium solubility of water in octanol at room temperature is reported to be about 5 mass percent. (https://doi.org/10.1007/s00706-003-0053-x ; https://doi.org/10.1021/je3001427)

So we should consider only the "wet" octanol box. The water box would contain an insignificant amount of octanol.

I made the conversions and everything looks coherent:
- MW water: 18
- MW octanol: 130
- water 27 mol % -> 486/9976 -> 4.87 weight %
- octanol 73 mol % -> 9490/9976 -> 95.13 weight %

Our current pure octanol box contains 512 molecules, so **the "wet" octanol box should contain 138 molecules of water and 374 molecules of octanol**.

**Comment by iorga** [comment]
Full-text files for the papers mentioned in the previous post:
- Solubility of Water in Octan-1-ol from (275 to 369) K, Brian E. Lang, Journal of Chemical & Engineering Data 2012 57 (8), 2221-2226 [Full-text](https://github.com/Becksteinlab/MDPOW/files/2544127/je3001427.pdf)
- Thermodynamics of the Solubility of Water in 1-Hexanol, 1-Octanol, 1-Decanol, and Cyclohexanol, Šegatin, N. & Klofutar, C. Monatshefte für Chemie (2004) 135: 241. [Full-text](https://github.com/Becksteinlab/MDPOW/files/2544128/Segatin-Klofutar2004_Article_ThermodynamicsOfTheSolubilityO.pdf)
- Octanol–Water Partition Coefficient Measurement by a Simple 1H NMR Method, Hemi Cumming and Christoph Rücker, ACS Omega 2017 2 (9), 6244-6249 [Full-text](https://github.com/Becksteinlab/MDPOW/files/2544129/acsomega.7b01102.pdf)

**Comment by orbeckst** [comment]
Closed by PR #103 and PR #121
